footer section completed
pda-mit/PDA-Website pull request #95
Opened 2021-12-26 13:47 UTC by R-V-Vighnesh

**Description**

This PR fixes #72 

**Notes for Reviewer**

the footer contains :

- PDA logo (PDA name and small description)
- social media icons
- Quick links
- location , phone number and mail id
- Sign Up button
- Copyrights

1. footer contents have been grouped into 4 sections with appropriate headings
2. scroll to top button has been designed and placed in the footer
3. footer has been made responsive
4. simple animations has have been implemented when buttons, links are hovered upon

- [ ] Frontend (Signup/Login)
- [ ] Backend (Login)
- [ ] Backend (Signup)
- [x] Homepage
- [ ] Others

teamwork by myself, @bala418 , @Bhuvanaa28
![PDA_footer_updated](https://user-images.githubusercontent.com/86763711/147410066-5e2b29ad-a3f0-48c2-a6b5-9f55668567c5.png)

2021-12-26 17:31 UTC, coding-geek21 requested changes
@R-V-Vighnesh Just minor changes to be done... Rest all looks good 👍🏼

2021-12-26 17:31 UTC, coding-geek21 commented on views/partial/footer.ejs
> +    <link rel="stylesheet" href="style.css">
Change this to 
`<link rel="stylesheet" href="css/footer.css">`

2021-12-26 17:31 UTC, coding-geek21 commented on views/partial/footer.ejs
> +    <h1>Scroll down to view the footer</h1><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
Also remove this line

2021-12-26 17:31 UTC, coding-geek21 commented on views/partial/footer.ejs
> +            <img src="public\img\pda-logo.png" alt="logo" class="logo">
`<img src="images\pda-logo.png" alt="logo" class="logo">`

Also fix the the logo image .. It looks shrinken 

![image](https://user-images.githubusercontent.com/53329034/147415561-f7b7a6da-dc4a-4f06-aafc-f25f88146c63.png)

2021-12-26 17:31 UTC, coding-geek21 commented on views/partial/footer.ejs
> +            <h3>Get in Touch</h3>
Place some gap below the title **Get in Touch**

![image](https://user-images.githubusercontent.com/53329034/147415594-37e6d02b-2807-437c-ab89-ad5287116255.png)

2021-12-26 17:31 UTC, coding-geek21 commented on views/partial/footer.ejs
> +            <span onclick="(function(){window.scrollTo({top: 0,left: 0,behavior: 'smooth'})})();"><i class="fa fa-arrow-circle-up"></i></span>
Place this at the end 

![image](https://user-images.githubusercontent.com/53329034/147415705-cbad8705-b4c1-437f-87a7-fd53be29c764.png)

2021-12-27 02:35 UTC, coding-geek21 commented on views/partial/footer.ejs
> +    <link rel="stylesheet" href="style.css">
Change this to 
`<link rel="stylesheet" href="css/footer.css">`

2021-12-27 02:37 UTC, coding-geek21 commented on views/partial/footer.ejs
> +    <link rel="stylesheet" href="style.css">
Change this to
<link rel="stylesheet" href="css/footer.css">

2021-12-27 10:51 UTC, R-V-Vighnesh commented
Snr i have made the required changes in code. Can you check whether this footer is appropriate?

![PDA_footer_NewUpdates](https://user-images.githubusercontent.com/86763711/147464721-abc7c4e7-974c-4463-a98b-39f25dba84bc.png)

2021-12-27 12:45 UTC, coding-geek21 commented
> Snr i have made the required changes in code. Can you check whether this footer is appropriate?
> 
> ![PDA_footer_NewUpdates](https://user-images.githubusercontent.com/86763711/147470088-d9e4c3d9-ebd8-499c-8519-484bf2d03170.png)

Looks good jnr 🤩🤩 Great work merging it ✨

2021-12-27 12:45 UTC, coding-geek21 approved these changes

2021-12-27 12:45 UTC, merged